const projectsData = [
    {
        id: 1,
        title: "Aladdin - Directory",
        category: ["Directory"],
        description: "Aladdin-EG is a comprehensive business directory in Egypt, serving as a primary source of information and guidance for various sectors. It offers users access to a wide range of business listings, contact details, advertisements, maps, city guides, and news, facilitating easy navigation and informed decision-making.",
        img: "assets/imgs/projects/aladdin-directory.png",
        date: "22 MAY",
        github: "https://github.com/HassanSalah25/aladdin-ref",
        link: "https://aladdin-eg.com/",
        tools: ["Laravel, ", "MySQL, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 2,
        title: "Neo Health Register",
        category: ["Healthcare"],
        description: "Neo Healthcare Center is a healthcare management platform designed to streamline appointment registration processes. Patients can schedule appointments for specific services with doctors, view available slots, and receive confirmations. Built with Laravel PHP, MySQL, and native HTML/CSS/JS, the system ensures security, high performance, and a smooth user experience for both patients and healthcare administrators.",
        img: "assets/imgs/projects/neo.png",
        date: "22 MAY",
        github: "https://github.com/HassanSalah25/neo-healthcare",
        link: "https://github.com/HassanSalah25/neo-healthcare",
        tools: ["Laravel, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 2,
        title: "Shoaa - Healthcare",
        category: ["Healthcare"],
        description: "Shoaa is a healthcare center website developed using WordPress, providing an efficient and user-friendly platform for patients to register appointments for various healthcare services with doctors. The website integrates customized WordPress features to streamline the appointment booking process while maintaining a clean and responsive design for optimal user experience on all devices.",
        img: "assets/imgs/projects/shoaa.png",
        date: "22 MAY",
        github: null,
        link: "https://shoaamc.com/",
        tools: ["WordPress, ", "PHP, ", "MySQL, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 3,
        title: "Cotton House Kidswear - E-Commerce",
        category: ["Ecommerce"],
        description: "CottonHouseKidsWear is an e-commerce website that sells custom clothing for all ages and genders. The platform is designed to offer an easy-to-use shopping experience, allowing customers to browse various categories of clothes, view product details, and purchase customized clothing items. Customers can select sizes, colors, and styles based on their preferences. The website is built using Laravel PHP, MySQL, and other modern web technologies to ensure high performance, security, and scalability. The front-end is clean and user-friendly, with responsive design ensuring that the site functions well on both mobile and desktop devices.",
        img: "assets/imgs/projects/ct.png",
        date: "16 JAN",
        github: "https://github.com/HassanSalah25/cottonhousekidswear",
        link: "https://github.com/HassanSalah25/cottonhousekidswear",
        tools: ["Laravel, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 4,
        title: "Grand Gate - Company Profile",
        category: ["Company", "Profile"],
        description: "Grand Gate is a portfolio website designed to showcase and sell premium gates for large buildings, including commercial, industrial, and residential spaces. Built using Laravel PHP, MySQL, and native HTML/CSS/JS, the platform provides a clean, professional presentation for high-quality gate designs. Customers can browse through categories, view detailed product information, and explore project galleries to find the perfect solution for their building needs. The website is fully responsive, ensuring optimal performance on all devices.",
        img: "assets/imgs/projects/grand-gate.png",
        date: "22 MAY",
        github: "https://github.com/HassanSalah25/grand-gate",
        link: "https://github.com/HassanSalah25/grand-gate",
        tools: ["Laravel, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 7,
        title: "Web Scraper - Scraper",
        category: ["Scraper", "Python"],
        description: "The Web Scraping project was built using Python and its powerful libraries, such as **BeautifulSoup**, **Scrapy**, and **Requests**, to extract structured data from popular websites like **Alibaba** and **YellowPages**. The project automates the process of collecting valuable information such as product listings, business details, and contact information for further analysis and business use.",
        img: "assets/imgs/projects/webscrapping.png",
        date: "08 MAY",
        github: null,
        link: null,
        tools: ["Python, ", "BeautifulSoup, ", "Scrapy, ", "Requests, ", "MySQL"],
    },
    {
        id: 9,
        title: "Modevia - Register",
        category: ["register"],
        description: "Modevia is a healthcare platform designed to streamline the process of booking appointments for healthcare services with doctors. Built using **Laravel** for the backend, **React.js** for the interactive user interface, and **MySQL** for data storage, the system ensures a smooth and secure experience for both patients and administrators. Patients can register appointments, view doctor availability, and manage their healthcare schedules seamlessly.",
        img: "assets/imgs/projects/modevia.png",
        date: "17 JUN",
        github: null,
        link: "http://test.modevia-clinic.com/",
        tools: ["Laravel, ", "React.js, ", "MySQL, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 3,
        title: "AT Store - E-Commerce",
        category: ["Ecommerce"],
        description: "An e-commerce platform for kids' clothing built with Laravel.",
        img: "assets/imgs/projects/atstore.png",
        date: "16 JAN",
        github: "https://github.com/HassanSalah25/cottonhousekidswear",
        link: "https://github.com/HassanSalah25/cottonhousekidswear",
        tools: ["Laravel, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 3,
        title: "Masterchef - E-Commerce",
        category: ["Ecommerce"],
        description: "An e-commerce platform for kids' clothing built with Laravel.",
        img: "assets/imgs/projects/masterchef.png",
        date: "16 JAN",
        github: null,
        link: null,
        tools: ["Laravel, ", "Vue.JS, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 8,
        title: "Ionology - Company Profile",
        category: ["Company", "Profile"],
        description: "A company profile website built with Laravel for a digital marketing agency in Saudi Arabia.",
        img: "assets/imgs/projects/ionology.png",
        date: "05 JUN",
        github: null,
        link: "http://ionology.sa/",
        tools: ["Laravel, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 10,
        title: "DUKE - E-Commerce",
        category: ["Ecommerce"],
        description: "An e-commerce platform built with WordPress for a Appliances store in Saudi Arabia.",
        img: "assets/imgs/projects/duke.png",
        date: "01 DEC",
        github: null,
        link: "http://dukeksa.com/",
        tools: ["WordPress, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 11,
        title: "Cordiana - ERP",
        category: ["erp"],
        description: "An ERP system built with Laravel for a company in Egypt.",
        img: "assets/imgs/projects/cordiana.png",
        date: "28 DEC",
        github: null,
        link: "https://cordiana-sys.com/",
        tools: ["Laravel, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 12,
        title: "Nota - Accountant",
        category: ["accounting"],
        description: "An accounting system built with Laravel for a company in Egypt.",
        img: "assets/imgs/projects/aladdin-directory.png",
        date: "28 DEC",
        github: null,
        link: "https://account.aladdin-eg.com/login",
        tools: ["Laravel, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 13,
        title: "Octahedron - ERP",
        category: ["erp"],
        description: "An ERP system built with Laravel. for a company in Egypt.",
        img: "assets/imgs/projects/octahedron.png",
        date: "28 DEC",
        github: null,
        link: "http://octahedron-sols.com/",
        tools: ["Laravel, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 14,
        title: "Paper Jewels - E-Commerce",
        category: ["Ecommerce"],
        description: "An e-commerce platform built with Laravel. for a company in Saudi Arabia.",
        img: "assets/imgs/projects/paper_jewels.png",
        date: "28 DEC",
        github: null,
        link: null,
        tools: ["Laravel, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 21,
        title: "Al Motqd - E-Commerce",
        category: ["Ecommerce"],
        description: "An e-commerce platform built with Laravel.",
        img: "assets/imgs/projects/ALMOTQD.png",
        date: "28 DEC",
        github: null,
        link: "https://almotqd.shafiqa-directory.com/",
        tools: ["Laravel, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 22,
        title: "KMG Castor - Ecommerce",
        category: ["Ecommerce"],
        description: "A company profile website built with OpenCart.",
        img: "assets/imgs/projects/kmg.png",
        date: "28 DEC",
        github: null,
        link: "http://kmgcastor.com/",
        tools: ["OpenCart, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 25,
        title: "Ragaie - Company Profile",
        category: ["Company", "Profile"],
        description: "A company profile website built with WordPress.",
        img: "assets/imgs/projects/ragaie.png",
        date: "29 DEC",
        github: null,
        link: "http://ragaie.com",
        tools: ["WordPress, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 29,
        title: "Mar Decor - Company Profile",
        category: ["Company", "Profile"],
        description: "A company profile website built with Laravel.",
        img: "assets/imgs/projects/mardecor.png",
        date: "05 JAN",
        github: null,
        link: "http://new.mar-decor.com/",
        tools: ["Laravel, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 28,
        title: "Corddigital - Company Profile",
        category: ["Company", "Profile"],
        description: "A company profile website built with Laravel.",
        img: "assets/imgs/projects/gohar.png",
        date: "05 JAN",
        github: null,
        link: "https://corddigital.com/",
        tools: ["Laravel, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 6,
        title: "Social Media Web App - Blogging",
        category: ["Blogging", "Social"],
        description: "A social media and blogging platform built with Laravel.",
        img: "assets/imgs/projects/gohar.png",
        date: "08 MAY",
        github: null,
        link: null,
        tools: ["Laravel, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 15,
        title: "Short URL Verse - Service",
        category: ["Service"],
        description: "A URL shortening service built with Laravel.",
        img: "assets/imgs/projects/gohar.png",
        date: "28 DEC",
        github: null,
        link: null,
        tools: ["Laravel, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 16,
        title: "QR Code Verse - Service",
        category: ["Service"],
        description: "A QR code generation service built with Laravel.",
        img: "assets/imgs/projects/gohar.png",
        date: "28 DEC",
        github: null,
        link: "https://qrcode.seowolves.net/account/sign-up",
        tools: ["Laravel, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 17,
        title: "V Card Verse - Service",
        category: ["Service"],
        description: "A digital business card service built with Laravel.",
        img: "assets/imgs/projects/gohar.png",
        date: "28 DEC",
        github: null,
        link: "http://vcard.seowolves.net",
        tools: ["Laravel, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 18,
        title: "Page Builder - Service",
        category: ["Service"],
        description: "A page builder tool built with Laravel.",
        img: "assets/imgs/projects/gohar.png",
        date: "28 DEC",
        github: null,
        link: null,
        tools: ["Laravel, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 19,
        title: "News Blogging - Blogging",
        category: ["blogging"],
        description: "A news blogging platform built with Laravel.",
        img: "assets/imgs/projects/gohar.png",
        date: "28 DEC",
        github: null,
        link: null,
        tools: ["Laravel, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 20,
        title: "Salon Beauty - Service",
        category: ["Service"],
        description: "A salon management system built with Laravel.",
        img: "assets/imgs/projects/gohar.png",
        date: "28 DEC",
        github: null,
        link: null,
        tools: ["Laravel, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 23,
        title: "German.C - Company Profile",
        category: ["Company", "Profile"],
        description: "A company profile website built with OpenCart.",
        img: "assets/imgs/projects/gohar.png",
        date: "28 DEC",
        github: null,
        link: null,
        tools: ["OpenCart, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 24,
        title: "E-Commerce Builder - E-Commerce",
        category: ["Ecommerce"],
        description: "An e-commerce platform builder built with Laravel.",
        img: "assets/imgs/projects/gohar.png",
        date: "28 DEC",
        github: null,
        link: null,
        tools: ["Laravel, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 26,
        title: "Moneyfellow - Service",
        category: ["Service"],
        description: "A financial service platform built with Django.",
        img: "assets/imgs/projects/gohar.png",
        date: "31 DEC",
        github: null,
        link: null,
        tools: ["Django, ", "MySQL, ", "Python, ", "HTML, ", "CSS, ", "JS"],
    },
    {
        id: 27,
        title: "Stockfly",
        category: ["Project"],
        description: "A project built with Laravel.",
        img: "assets/imgs/projects/gohar.png",
        date: "31 DEC",
        github: null,
        link: null,
        tools: ["Laravel, ", "MySQL, ", "PHP, ", "HTML, ", "CSS, ", "JS"],
    },
];

export default projectsData;